import {
  // Buttons
  Button,
  SocialAuthButton,
  FilterChip,
  // Navigation
  Sidebar,
  TopBar,
  Breadcrumbs,
  LandingNav,
  Tabs,
  ViewToggle,
  // Cards
  SessionCard,
  TournamentCard,
  ClubCard,
  MissionCard,
  FederationCard,
  PlayerCard,
  StatCard,
  ArticleCard,
  GameTabCard,
  GameCard,
  GameStatCard,
  PricingCard,
  NewsCard,
  AccountConnectionCard,
  // Forms
  TextInput,
  SearchInput,
  Select,
  Toggle,
  PasswordInput,
  ChatInput,
  // Data
  StatusPill,
  Badge,
  ProgressBar,
  CountdownTimer,
  LeaderboardRow,
  DataTable,
  PlayerTableRow,
  PlayerTableHeader,
  // Chat
  ChatMessage,
  ChatListItem,
  // Layout
  PageHeader,
  SectionHeader,
  HeroBanner,
  SettingsSidebar,
  GameHeroBanner,
  FederationHero,
  QuickFacts,
  Footer,
  // Overlays
  Modal,
  FilterDrawer,
  SaveChangesBar,
  // Micro
  Avatar,
  AvatarGroup,
  Divider,
  GameIcon,
  GameIconGroup,
} from "@/components";

import {
  Home,
  Users,
  Trophy,
  Swords,
  Gamepad2,
  Search,
  Filter,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  Star,
  Clock,
  Calendar,
  MapPin,
  Shield,
  Crown,
  Medal,
  Target,
  Zap,
  Bell,
  Settings,
  Plus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  Eye,
  EyeOff,
  MessageSquare,
  Send,
  Paperclip,
  Smile,
  SlidersHorizontal,
  MoreHorizontal,
  MoreVertical,
  Edit,
  Trash2,
  Copy,
  Share2,
  ExternalLink,
  Globe,
  Flag,
  User,
  UserPlus,
  LogOut,
  Lock,
  Unlock,
  Heart,
  Bookmark,
  Download,
  Upload,
  RefreshCw,
  AlertCircle,
  Info,
  CheckCircle,
  XCircle,
  Menu,
  Hash,
  Flame,
  TrendingUp,
  Award,
  Monitor,
  List,
  LayoutGrid,
  Link,
} from "lucide-react";

import { useState, useEffect, useMemo, useCallback, Fragment } from "react";

export const liveScope = {
  // React
  useState,
  useEffect,
  useMemo,
  useCallback,
  Fragment,

  // Buttons
  Button,
  SocialAuthButton,
  FilterChip,

  // Navigation
  Sidebar,
  TopBar,
  Breadcrumbs,
  LandingNav,
  Tabs,
  ViewToggle,

  // Cards
  SessionCard,
  TournamentCard,
  ClubCard,
  MissionCard,
  FederationCard,
  PlayerCard,
  StatCard,
  ArticleCard,
  GameTabCard,
  GameCard,
  GameStatCard,
  PricingCard,
  NewsCard,
  AccountConnectionCard,

  // Forms
  TextInput,
  SearchInput,
  Select,
  Toggle,
  PasswordInput,
  ChatInput,

  // Data
  StatusPill,
  Badge,
  ProgressBar,
  CountdownTimer,
  LeaderboardRow,
  DataTable,
  PlayerTableRow,
  PlayerTableHeader,

  // Chat
  ChatMessage,
  ChatListItem,

  // Layout
  PageHeader,
  SectionHeader,
  HeroBanner,
  SettingsSidebar,
  GameHeroBanner,
  FederationHero,
  QuickFacts,
  Footer,

  // Overlays
  Modal,
  FilterDrawer,
  SaveChangesBar,

  // Micro
  Avatar,
  AvatarGroup,
  Divider,
  GameIcon,
  GameIconGroup,

  // Icons
  Home, Users, Trophy, Swords, Gamepad2, Search, Filter,
  ChevronRight, ChevronDown, ChevronUp, ChevronLeft,
  Star, Clock, Calendar, MapPin, Shield, Crown, Medal,
  Target, Zap, Bell, Settings, Plus, X, Check,
  ArrowRight, ArrowLeft, Eye, EyeOff,
  MessageSquare, Send, Paperclip, Smile,
  SlidersHorizontal, MoreHorizontal, MoreVertical,
  Edit, Trash2, Copy, Share2, ExternalLink,
  Globe, Flag, User, UserPlus, LogOut,
  Lock, Unlock, Heart, Bookmark, Download, Upload,
  RefreshCw, AlertCircle, Info, CheckCircle, XCircle,
  Menu, Hash, Flame, TrendingUp, Award, Monitor,
  List, LayoutGrid, Link,
};
