import {
  // Buttons
  Button,
  SocialAuthButton,
  FilterChip,
  // Navigation
  Sidebar,
  TopBar,
  Breadcrumbs,
  LandingNav,
  Tabs,
  ViewToggle,
  // Cards
  SessionCard,
  TournamentCard,
  ClubCard,
  MissionCard,
  FederationCard,
  PlayerCard,
  StatCard,
  ArticleCard,
  GameTabCard,
  GameCard,
  GameStatCard,
  PricingCard,
  NewsCard,
  AccountConnectionCard,
  // Forms
  TextInput,
  SearchInput,
  Select,
  Toggle,
  PasswordInput,
  ChatInput,
  // Data
  StatusPill,
  Badge,
  ProgressBar,
  CountdownTimer,
  LeaderboardRow,
  DataTable,
  PlayerTableRow,
  PlayerTableHeader,
  // Chat
  ChatMessage,
  ChatListItem,
  // Layout
  PageHeader,
  SectionHeader,
  HeroBanner,
  SettingsSidebar,
  GameHeroBanner,
  FederationHero,
  QuickFacts,
  Footer,
  // Overlays
  Modal,
  FilterDrawer,
  SaveChangesBar,
  // Micro
  Avatar,
  AvatarGroup,
  Divider,
  GameIcon,
  GameIconGroup,
} from "@/components";

import {
  Home,
  Users,
  Trophy,
  Swords,
  Gamepad2,
  Search,
  Filter,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  Star,
  Clock,
  Calendar,
  MapPin,
  Shield,
  Crown,
  Medal,
  Target,
  Zap,
  Bell,
  Settings,
  Plus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  Eye,
  EyeOff,
  MessageSquare,
  Send,
  Paperclip,
  Smile,
  SlidersHorizontal,
  MoreHorizontal,
  MoreVertical,
  Edit,
  Trash2,
  Copy,
  Share2,
  ExternalLink,
  Globe,
  Globe2,
  Flag,
  User,
  UserPlus,
  LogOut,
  Lock,
  Unlock,
  Heart,
  Bookmark,
  Download,
  Upload,
  RefreshCw,
  AlertCircle,
  Info,
  CheckCircle,
  XCircle,
  Menu,
  Hash,
  Flame,
  TrendingUp,
  Award,
  Monitor,
  List,
  LayoutGrid,
  Link,
  Tag,
  Sparkles,
  Loader2,
  RotateCcw,
  Smartphone,
  Maximize2,
  Minimize2,
  Code2,
  History,
  Phone,
  PhoneCall,
  Video,
  Mic,
  MicOff,
  Volume2,
  VolumeX,
  Wifi,
  WifiOff,
  Camera,
  Image,
  FileText,
  File,
  Folder,
  FolderOpen,
  Mail,
  Inbox,
  Archive,
  Trash,
  PenLine,
  Pencil,
  CircleDot,
  Circle,
  Square,
  Triangle,
  Hexagon,
  Grip,
  GripVertical,
  Move,
  BarChart2,
  PieChart,
  Activity,
  Layers,
  Package,
  Gift,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Percent,
  AtSign,
  Terminal,
  Code,
  Braces,
  Database,
  Server,
  Cloud,
  CloudUpload,
  CloudDownload,
  Cpu,
  HardDrive,
  Headphones,
  Speaker,
  Radio,
  Tv,
  Power,
  Battery,
  BatteryCharging,
  Bluetooth,
  Cast,
  Crosshair,
  Navigation,
  Compass,
  Map,
  Sun,
  Moon,
  CloudRain,
  Thermometer,
  Droplets,
  Wind,
  Anchor,
  Rocket,
  Plane,
  Car,
  Bike,
  Ship,
  Train,
  Building,
  Building2,
  Warehouse,
  Store,
  School,
  Church,
  Landmark,
  Trees,
  Mountain,
  Waves,
  Leaf,
  Flower2,
  Bug,
  Bot,
  Brain,
  Fingerprint,
  ScanFace,
  QrCode,
  Barcode,
  Printer,
  Save,
  ClipboardList,
  ClipboardCheck,
  ListChecks,
  ListOrdered,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Type,
  Heading1,
  Heading2,
  Heading3,
  Quote,
  Table,
  Columns,
  Rows,
  PanelLeft,
  PanelRight,
  SplitSquareHorizontal,
  Expand,
  Shrink,
  ZoomIn,
  ZoomOut,
  RotateCw,
  Repeat,
  Shuffle,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  FastForward,
  Rewind,
  StepForward,
  StepBack,
  CirclePlay,
  CirclePause,
  CircleStop,
  ThumbsUp,
  ThumbsDown,
  HandMetal,
  PartyPopper,

  Cake,
  Baby,
  Dog,
  Cat,
  Fish,
  Bird,
  Rabbit,
  Squirrel,
  PawPrint,
  Footprints,
  Accessibility,
  AlertTriangle,
  Ban,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  KeyRound,
  Key,
  Scan,
  ScanLine,
  Timer,
  TimerOff,
  Hourglass,
  CalendarDays,
  CalendarCheck,
  CalendarClock,
  CalendarPlus,
  CalendarMinus,
  Wand2,
  Palette,
  Paintbrush,
  Eraser,
  Pipette,
  Scissors,
  Ruler,
  Hammer,
  Wrench,
  Nut,
  Cog,
  SlidersVertical,
  Plug,
  Cable,
  Usb,
  Signal,
  SignalHigh,
  SignalLow,
  SignalZero,
  Voicemail,
  MessageCircle,
  MessagesSquare,
  Reply,
  ReplyAll,
  Forward,
  CornerUpRight,
  CornerUpLeft,
  CornerDownRight,
  CornerDownLeft,
  ArrowUp,
  ArrowDown,
  ArrowUpRight,
  ArrowDownRight,
  ArrowUpLeft,
  ArrowDownLeft,
  ChevronsUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  MoveUp,
  MoveDown,
  MoveLeft,
  MoveRight,
  Minus,
  Equal,
  Divide,
  Sigma,
  Binary,
  Hash as HashIcon,
  Asterisk,
  Infinity,
  Regex,
} from "lucide-react";

import { useState, useEffect, useMemo, useCallback, Fragment } from "react";
import { MEDIA_LIBRARY } from "@/lib/media-library";

export const liveScope = {
  // React
  useState,
  useEffect,
  useMemo,
  useCallback,
  Fragment,

  // Buttons
  Button,
  SocialAuthButton,
  FilterChip,

  // Navigation
  Sidebar,
  TopBar,
  Breadcrumbs,
  LandingNav,
  Tabs,
  ViewToggle,

  // Cards
  SessionCard,
  TournamentCard,
  ClubCard,
  MissionCard,
  FederationCard,
  PlayerCard,
  StatCard,
  ArticleCard,
  GameTabCard,
  GameCard,
  GameStatCard,
  PricingCard,
  NewsCard,
  AccountConnectionCard,

  // Forms
  TextInput,
  SearchInput,
  Select,
  Toggle,
  PasswordInput,
  ChatInput,

  // Data
  StatusPill,
  Badge,
  ProgressBar,
  CountdownTimer,
  LeaderboardRow,
  DataTable,
  PlayerTableRow,
  PlayerTableHeader,

  // Chat
  ChatMessage,
  ChatListItem,

  // Layout
  PageHeader,
  SectionHeader,
  HeroBanner,
  SettingsSidebar,
  GameHeroBanner,
  FederationHero,
  QuickFacts,
  Footer,

  // Overlays
  Modal,
  FilterDrawer,
  SaveChangesBar,

  // Micro
  Avatar,
  AvatarGroup,
  Divider,
  GameIcon,
  GameIconGroup,
  MEDIA_LIBRARY,

  // Icons
  Home, Users, Trophy, Swords, Gamepad2, Search, Filter,
  ChevronRight, ChevronDown, ChevronUp, ChevronLeft,
  Star, Clock, Calendar, MapPin, Shield, Crown, Medal,
  Target, Zap, Bell, Settings, Plus, X, Check,
  ArrowRight, ArrowLeft, Eye, EyeOff,
  MessageSquare, Send, Paperclip, Smile,
  SlidersHorizontal, MoreHorizontal, MoreVertical,
  Edit, Trash2, Copy, Share2, ExternalLink,
  Globe, Flag, User, UserPlus, LogOut,
  Lock, Unlock, Heart, Bookmark, Download, Upload,
  RefreshCw, AlertCircle, Info, CheckCircle, XCircle,
  Menu, Hash, Flame, TrendingUp, Award, Monitor,
  List, LayoutGrid, Link,
  Globe2, Tag, Sparkles, Loader2, RotateCcw, Smartphone, Maximize2, Minimize2, Code2, History,
  Phone, PhoneCall, Video, Mic, MicOff, Volume2, VolumeX, Wifi, WifiOff, Camera, Image,
  FileText, File, Folder, FolderOpen, Mail, Inbox, Archive, Trash, PenLine, Pencil,
  CircleDot, Circle, Square, Triangle, Hexagon, Grip, GripVertical, Move,
  BarChart2, PieChart, Activity, Layers, Package, Gift, ShoppingCart, CreditCard, DollarSign, Percent,
  AtSign, Terminal, Code, Braces, Database, Server, Cloud, CloudUpload, CloudDownload,
  Cpu, HardDrive, Headphones, Speaker, Radio, Tv, Power, Battery, BatteryCharging,
  Bluetooth, Cast, Crosshair, Navigation, Compass, Map, Sun, Moon, CloudRain, Thermometer,
  Droplets, Wind, Anchor, Rocket, Plane, Car, Bike, Ship, Train,
  Building, Building2, Warehouse, Store, School, Church, Landmark,
  Trees, Mountain, Waves, Leaf, Flower2, Bug, Bot, Brain, Fingerprint, ScanFace, QrCode, Barcode,
  Printer, Save, ClipboardList, ClipboardCheck, ListChecks, ListOrdered,
  AlignLeft, AlignCenter, AlignRight, AlignJustify,
  Bold, Italic, Underline, Strikethrough, Type, Heading1, Heading2, Heading3, Quote,
  Table, Columns, Rows, PanelLeft, PanelRight, SplitSquareHorizontal,
  Expand, Shrink, ZoomIn, ZoomOut, RotateCw, Repeat, Shuffle,
  Play, Pause, SkipForward, SkipBack, FastForward, Rewind, StepForward, StepBack,
  CirclePlay, CirclePause, CircleStop, ThumbsUp, ThumbsDown, HandMetal, PartyPopper,
  Cake, Dog, Cat, Fish, Bird, Rabbit, Squirrel, PawPrint, Footprints,
  Accessibility, AlertTriangle, Ban, ShieldAlert, ShieldCheck, ShieldOff, KeyRound, Key,
  Scan, ScanLine, Timer, TimerOff, Hourglass,
  CalendarDays, CalendarCheck, CalendarClock, CalendarPlus, CalendarMinus,
  Wand2, Palette, Paintbrush, Eraser, Pipette, Scissors, Ruler, Hammer, Wrench, Nut, Cog,
  SlidersVertical, Plug, Cable, Usb, Signal, SignalHigh, SignalLow, SignalZero,
  Voicemail, MessageCircle, MessagesSquare, Reply, ReplyAll, Forward,
  CornerUpRight, CornerUpLeft, CornerDownRight, CornerDownLeft,
  ArrowUp, ArrowDown, ArrowUpRight, ArrowDownRight, ArrowUpLeft, ArrowDownLeft,
  ChevronsUp, ChevronsDown, ChevronsLeft, ChevronsRight,
  MoveUp, MoveDown, MoveLeft, MoveRight,
  Minus, Equal, Divide, Sigma, Binary, Asterisk, Infinity, Regex,
};
